import type { DiagnosisResult } from '@/types'
import { isRTL } from '@/config/countries'

export const generateDiagnosisPDF = (
  diagnosis: DiagnosisResult,
  language: string,
  t: (key: any, defaultValue?: any) => string
): void => {
  const isRtl = isRTL(language)
  const formattedDate = new Date(diagnosis.timestamp || Date.now()).toLocaleDateString(language, {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })

  // Dynamic translated values
  const cropText = t(`crops.${diagnosis.crop}`, diagnosis.crop)
  const diseaseText = t(`diseases.${diagnosis.disease}`, diagnosis.disease)
  const severityText = t(`diagnose.result.severity.${diagnosis.severity}`, diagnosis.severity)
  const symptomsList = diagnosis.symptoms.map(s => t(`symptoms.${s}`, s))
  const actionsList = diagnosis.actions.map(a => t(`actions.${a}`, a))

  // PDF Titles and Labels from i18n
  const pdfTitle = t('pdf.title', 'Crop Health Diagnosis Report')
  const cropLabel = t('pdf.cropLabel', 'Crop Name')
  const diseaseLabel = t('pdf.diseaseLabel', 'Diagnosed Issue / Disease')
  const confidenceLabel = t('pdf.confidenceLabel', 'Confidence Score')
  const severityLabel = t('pdf.severityLabel', 'Severity Level')
  const symptomsHeading = t('pdf.symptomsHeading', 'Observed Symptoms')
  const recommendationsHeading = t('pdf.recommendationsHeading', 'Recommended Treatment & Actions')
  const expertReviewMessage = t('pdf.expertReviewMessage', 'AI diagnosis is informational and should not replace professional agricultural advice.')
  const dateLabel = t('pdf.dateLabel', 'Date')
  const footerText = t('pdf.footer', 'Generated by CROPOCTOR — BRICS Agricultural Intelligence Platform')
  const matchText = t('diagnose.match', 'match')

  // Construct styled printable HTML with Google Fonts for Devanagari, Gujarati, Arabic & Latin
  const htmlContent = `
<!DOCTYPE html>
<html lang="${language}" dir="${isRtl ? 'rtl' : 'ltr'}">
<head>
  <meta charset="UTF-8">
  <title>${pdfTitle} - CROPOCTOR</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Noto+Naskh+Arabic:wght@400;600;700&family=Noto+Sans+Devanagari:wght@400;600;700&family=Noto+Sans+Gujarati:wght@400;600;700&family=Plus+Jakarta+Sans:wght@400;600;700;800&display=swap" rel="stylesheet">
  <style>
    * {
      box-sizing: border-box;
      margin: 0;
      padding: 0;
    }
    body {
      font-family: 'Plus Jakarta Sans', 'Noto Sans Devanagari', 'Noto Sans Gujarati', 'Noto Naskh Arabic', sans-serif;
      background: #ffffff;
      color: #1c1917;
      line-height: 1.6;
      padding: 30px;
      max-width: 800px;
      margin: 0 auto;
      direction: ${isRtl ? 'rtl' : 'ltr'};
    }
    .header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      border-bottom: 3px solid #2e7d32;
      padding-bottom: 16px;
      margin-bottom: 24px;
    }
    .logo-container {
      display: flex;
      align-items: center;
      gap: 12px;
    }
    .logo-badge {
      width: 44px;
      height: 44px;
      background: #2e7d32;
      color: #ffffff;
      border-radius: 12px;
      display: flex;
      align-items: center;
      justify-content: center;
      font-size: 24px;
    }
    .brand-name {
      font-size: 22px;
      font-weight: 800;
      color: #2e7d32;
      letter-spacing: -0.5px;
    }
    .brand-tagline {
      font-size: 11px;
      color: #78716c;
      font-weight: 600;
    }
    .doc-title {
      font-size: 18px;
      font-weight: 700;
      color: #1c1917;
      text-align: ${isRtl ? 'left' : 'right'};
    }
    .doc-date {
      font-size: 12px;
      color: #78716c;
    }

    .meta-grid {
      display: grid;
      grid-template-columns: repeat(2, 1fr);
      gap: 16px;
      background: #fdfbf7;
      border: 1px solid #e7e5e4;
      border-radius: 16px;
      padding: 20px;
      margin-bottom: 24px;
    }
    .meta-item {
      display: flex;
      flex-direction: column;
    }
    .meta-label {
      font-size: 11px;
      font-weight: 700;
      text-transform: uppercase;
      letter-spacing: 0.5px;
      color: #78716c;
      margin-bottom: 4px;
    }
    .meta-value {
      font-size: 16px;
      font-weight: 700;
      color: #1c1917;
    }
    .badge {
      display: inline-block;
      padding: 4px 10px;
      border-radius: 8px;
      font-size: 12px;
      font-weight: 700;
      width: fit-content;
    }
    .badge-green { background: #e8f5e9; color: #2e7d32; }
    .badge-warning { background: #fff3e0; color: #e65100; }

    .section {
      margin-bottom: 24px;
    }
    .section-title {
      font-size: 15px;
      font-weight: 700;
      color: #2e7d32;
      border-bottom: 1px solid #e7e5e4;
      padding-bottom: 8px;
      margin-bottom: 12px;
      display: flex;
      align-items: center;
      gap: 8px;
    }
    .item-list {
      list-style: none;
      padding: 0;
    }
    .item-list li {
      position: relative;
      padding-${isRtl ? 'right' : 'left'}: 24px;
      margin-bottom: 8px;
      font-size: 14px;
      font-weight: 500;
      color: #292524;
    }
    .item-list li::before {
      content: "•";
      position: absolute;
      ${isRtl ? 'right' : 'left'}: 8px;
      color: #2e7d32;
      font-weight: bold;
      font-size: 18px;
    }

    .disclaimer {
      background: #fefce8;
      border: 1px solid #fef08a;
      border-radius: 12px;
      padding: 14px;
      font-size: 12px;
      color: #854d0e;
      margin-top: 30px;
      margin-bottom: 30px;
    }

    .footer {
      border-top: 1px solid #e7e5e4;
      padding-top: 16px;
      text-align: center;
      font-size: 11px;
      color: #a8a29e;
      font-weight: 600;
    }

    @media print {
      body {
        padding: 0;
      }
      .no-print {
        display: none !important;
      }
    }
  </style>
</head>
<body>

  <div class="header">
    <div class="logo-container">
      <div class="logo-badge">🌱</div>
      <div>
        <div class="brand-name">CROPOCTOR</div>
        <div class="brand-tagline">BRICS Agricultural Intelligence</div>
      </div>
    </div>
    <div>
      <div class="doc-title">${pdfTitle}</div>
      <div class="doc-date">${dateLabel}: ${formattedDate}</div>
    </div>
  </div>

  <div class="meta-grid">
    <div class="meta-item">
      <span class="meta-label">${cropLabel}</span>
      <span class="meta-value">${cropText}</span>
    </div>
    <div class="meta-item">
      <span class="meta-label">${diseaseLabel}</span>
      <span class="meta-value">${diseaseText}</span>
    </div>
    <div class="meta-item">
      <span class="meta-label">${confidenceLabel}</span>
      <span class="meta-value badge badge-green">${diagnosis.confidence}% ${matchText}</span>
    </div>
    <div class="meta-item">
      <span class="meta-label">${severityLabel}</span>
      <span class="meta-value badge badge-warning">${severityText}</span>
    </div>
  </div>

  <div class="section">
    <div class="section-title">🔍 ${symptomsHeading}</div>
    <ul class="item-list">
      ${symptomsList.map(s => `<li>${s}</li>`).join('')}
    </ul>
  </div>

  <div class="section">
    <div class="section-title">✅ ${recommendationsHeading}</div>
    <ul class="item-list">
      ${actionsList.map(a => `<li>${a}</li>`).join('')}
    </ul>
  </div>

  <div class="disclaimer">
    ⚠️ <strong>Notice:</strong> ${expertReviewMessage}
  </div>

  <div class="footer">
    ${footerText}
  </div>

  <script>
    window.onload = function() {
      setTimeout(function() {
        window.print();
      }, 400);
    };
  </script>
</body>
</html>
  `

  // Use hidden print iframe to trigger clean browser PDF print dialog
  let iframe = document.getElementById('cropoctor-pdf-iframe') as HTMLIFrameElement | null
  if (!iframe) {
    iframe = document.createElement('iframe')
    iframe.id = 'cropoctor-pdf-iframe'
    iframe.style.position = 'fixed'
    iframe.style.right = '0'
    iframe.style.bottom = '0'
    iframe.style.width = '0'
    iframe.style.height = '0'
    iframe.style.border = 'none'
    document.body.appendChild(iframe)
  }

  const iframeDoc = iframe.contentWindow?.document || iframe.contentDocument
  if (iframeDoc) {
    iframeDoc.open()
    iframeDoc.write(htmlContent)
    iframeDoc.close()
  }
}
